### PR TITLE
Added D8 branch to readme

### PR DESCRIPTION
**Pull request by lewisnyman**

### CODE REVIEW

**Comment by axe312ger** [comment]
Thanks. But please consider that we are currently late in merging our newest code into this repository. It might not work for Drupal 8  - RC2.

**Comment by yannickoo** [comment]
The branch for D8 is named `d8`? I thought we have sth. like `7.x-1.x` and `8.x-1.x` - maybe we can change that later on.

Let's put the branch thing into the line above so we have `git clone --branch d8 git@github.com:wunderkraut/nameless.git` :)

**Comment by yannickoo** [comment]
Okay, @axe312ger was few seconds faster than me with commenting :bomb:

**Comment by lewisnyman** [comment]
hmm ok, I can help bring it up to speed with RC2 if you want to merge in soon

**Pull request merged**
